
(PGM, NAME="zzz SERIAL NUMBERS", TYPE="A2100_274", EXEMODE="STANDARD", PATH="PATHALL", ACCESS="OPEN", CREATED="THU APR 10 2014 13:34:37", MODIFIED="THU APR 10 2014 13:34:37", LEVEL="1")
:
[@SERNUM]=246035
:1
[START_MAIN]
[@DIGIT_1]=0
[@DIGIT_2]=0
[@DIGIT_3]=0
[@DIGIT_4]=0
[@DIGIT_5]=0
[@DIGIT_6]=0
[@TEMP]=[@SERNUM]
[@COUNT]=0
[START_6]
(IF[@TEMP]<100000 GOTO[END_6])
[@DIGIT_6]=[@DIGIT_6]+1
[@TEMP]=[@TEMP]-100000
(GOTO[START_6])
[END_6]
[@COUNT]=0
[START_5]
(IF[@TEMP]<10000 GOTO[END_5])
[@DIGIT_5]=[@DIGIT_5]+1
[@TEMP]=[@TEMP]-10000
(GOTO[START_5])
[END_5]
[@COUNT]=0
[START_4]
(IF[@TEMP]<1000 GOTO[END_4])
[@DIGIT_4]=[@DIGIT_4]+1
[@TEMP]=[@TEMP]-1000
(GOTO[START_4])
[END_4]
[@COUNT]=0
[START_3]
(IF[@TEMP]<100 GOTO[END_3])
[@DIGIT_3]=[@DIGIT_3]+1
[@TEMP]=[@TEMP]-100
(GOTO[START_3])
[END_3]
[@COUNT]=0
[START_2]
(IF[@TEMP]<10 GOTO[END_2])
[@DIGIT_2]=[@DIGIT_2]+1
[@TEMP]=[@TEMP]-10
(GOTO[START_2])
[END_2]
[@COUNT]=0
[START_1]
(IF[@TEMP]<1 GOTO[END_1])
[@DIGIT_1]=[@DIGIT_1]+1
[@TEMP]=[@TEMP]-1
(GOTO[START_1])
[END_1]
; MOVE TO FIRST POSITION IN ABSOLUTE COORDS
[@ENG_DIGIT]=[@DIGIT_1]
(CLS,"ENGRAVE")
; MOVE TO SECOND POSITION IN ABSOLUTE COORDS
[@ENG_DIGIT]=[@DIGIT_2]
(CLS,"ENGRAVE")
; MOVE TO THIRD POSITION IN ABSOLUTE COORDS
[@ENG_DIGIT]=[@DIGIT_3]
(CLS,"ENGRAVE")
; MOVE TO FOURTH POSITION IN ABSOLUTE COORDS
[@ENG_DIGIT]=[@DIGIT_4]
(CLS,"ENGRAVE")
; MOVE TO FIFTH POSITION IN ABSOLUTE COORDS
[@ENG_DIGIT]=[@DIGIT_5]
(CLS,"ENGRAVE")
; MOVE TO SIXTH POSITION IN ABSOLUTE COORDS
[@ENG_DIGIT]=[@DIGIT_6]
(CLS,"ENGRAVE")
M01
[@SERNUM]=[@SERNUM]+1
(GOTO[START_MAIN])
M30
(DFS,"ENGRAVE")
(IF[@ENG_DIGIT]=1 GOTO[ENG_1])
(IF[@ENG_DIGIT]=2 GOTO[ENG_2])
(IF[@ENG_DIGIT]=3 GOTO[ENG_3])
(IF[@ENG_DIGIT]=4 GOTO[ENG_4])
(IF[@ENG_DIGIT]=5 GOTO[ENG_5])
(IF[@ENG_DIGIT]=6 GOTO[ENG_6])
(IF[@ENG_DIGIT]=7 GOTO[ENG_7])
(IF[@ENG_DIGIT]=8 GOTO[ENG_8])
(IF[@ENG_DIGIT]=9 GOTO[ENG_9])
(CLS,"ENGRAVE_0")
(GOTO[ENG_FINISH])
[ENG_1]
(CLS,"ENGRAVE_1")
(GOTO[ENG_FINISH])
[ENG_2]
(CLS,"ENGRAVE_2")
(GOTO[ENG_FINISH])
[ENG_3]
(CLS,"ENGRAVE_3")
(GOTO[ENG_FINISH])
[ENG_4]
(CLS,"ENGRAVE_4")
(GOTO[ENG_FINISH])
[ENG_5]
(CLS,"ENGRAVE_5")
(GOTO[ENG_FINISH])
[ENG_6]
(CLS,"ENGRAVE_6")
(GOTO[ENG_FINISH])
[ENG_7]
(CLS,"ENGRAVE_7")
(GOTO[ENG_FINISH])
[ENG_8]
(CLS,"ENGRAVE_8")
(GOTO[ENG_FINISH])
[ENG_9]
(CLS,"ENGRAVE_9")
[ENG_FINISH]
(ENS)
(DFS,"ENGRAVE_0")
(ENS)
(DFS,"ENGRAVE_1")
(ENS)
(DFS,"ENGRAVE_2")
(ENS)
(DFS,"ENGRAVE_3")
(ENS)
(DFS,"ENGRAVE_4")
(ENS)
(DFS,"ENGRAVE_5")
(ENS)
(DFS,"ENGRAVE_6")
(ENS)
(DFS,"ENGRAVE_7")
(ENS)
(DFS,"ENGRAVE_8")
(ENS)
(DFS,"ENGRAVE_9")
(ENS)
